/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacheranaguapotable;

import backupData.RespaldoAutomatico;
import backupData.VentanaRespaldo;
import helpers.sql.SqlRespaldo;
import helpers.sql.SqlUsuarios;
import helpers.sql.clases.ComboBoxUsuarios;
import helpers.sql.clases.FiltradoUsuarios;
import helpers.sql.clases.HistorialPagos;
import helpers.sql.clases.InfoRecibo;
import helpers.sql.clases.MostrarPagos;
import helpers.sql.clases.MostrarUsuarios;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import reportes.VerReportes;
import sistemacheranaguapotable.bd.ConexionBd;

/**
 *
 * @author jafeth888
 */
public class MainJFrame extends javax.swing.JFrame {
    ConexionBd cc= ConexionBd.obtenerInstancia();
    Connection cn= cc.conexion();
    ComboBoxUsuarios instanciaComboBoxUsuarios=new ComboBoxUsuarios();
    public static String modificando="no";
    
    /*Variables para actualizar la tablaPagos en la pestania cobros al actulizar usuarios en la pestania usuarios*/
    public static String nombreStatic="",apellidoPaternoStatic="",apellidoMaternoStatic="",domicilioStatic="", barrioStatic="";
    /*fin de variables para actualizar tabla pagos*/
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        botonModificarUsuario.setEnabled(false);
        jyearPeriodo1.setYear(jyearPeriodo2.getYear()-20);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuUsuarios = new javax.swing.JPopupMenu();
        jMenuItemCobrar = new javax.swing.JMenuItem();
        jPopupMenuRegistroUsuarios = new javax.swing.JPopupMenu();
        jMenuItemModificarRegistroUsuarios = new javax.swing.JMenuItem();
        jMenuItemEliminarRegistroUsuarios = new javax.swing.JMenuItem();
        jPopupMenuHistorialRecibos = new javax.swing.JPopupMenu();
        jMenuItemVerRecibo = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelUsuarios = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtextFieldUserNoCliente = new javax.swing.JTextField();
        jtextFieldUserNoContrato = new javax.swing.JTextField();
        jtextFieldUserNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtextFieldUserApaterno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtextFieldUserAmaterno = new javax.swing.JTextField();
        jtextFieldUserTelefono = new javax.swing.JTextField();
        jtextFieldUserBarrio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtextFieldUserDomicilio = new javax.swing.JTextField();
        jComboBoxDescuentos = new javax.swing.JComboBox<>();
        jComboBoxTarifas = new javax.swing.JComboBox<>();
        botonRegistrarUsuario = new javax.swing.JButton();
        botonModificarUsuario = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPaneRegistroUsuarios = new javax.swing.JScrollPane();
        tablaRegistroUsuarios = new javax.swing.JTable();
        botonFiltrarUsuarios = new javax.swing.JButton();
        jButtonUsuariosEliminados = new javax.swing.JButton();
        jPanelCobros = new javax.swing.JPanel();
        jScrollPaneUsuarios = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        botonFactura = new javax.swing.JButton();
        botonM = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        buscadorNombre = new javax.swing.JTextField();
        buscadorApaterno = new javax.swing.JTextField();
        buscadorAmaterno = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        buscadorDomicilio = new javax.swing.JTextField();
        buscadorBarrio = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jyearPeriodo2 = new com.toedter.calendar.JYearChooser();
        jLabel20 = new javax.swing.JLabel();
        jyearPeriodo1 = new com.toedter.calendar.JYearChooser();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetallePagos = new javax.swing.JTable();
        botonGestionDescuentos = new javax.swing.JButton();
        botonGestionTarifas = new javax.swing.JButton();
        botonPagoMinimo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelValueDeudaTotal = new javax.swing.JLabel();
        botonRespaldoDatos = new javax.swing.JButton();
        botonReportes = new javax.swing.JButton();
        jPanelPagos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        botonFiltrarPagos = new javax.swing.JButton();
        jScrollPanePagos = new javax.swing.JScrollPane();
        tablaHistorialRecibos = new javax.swing.JTable();
        botonConsultarPago = new javax.swing.JButton();

        jMenuItemCobrar.setText("Cobrar");
        jMenuItemCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCobrarActionPerformed(evt);
            }
        });
        jPopupMenuUsuarios.add(jMenuItemCobrar);

        jMenuItemModificarRegistroUsuarios.setText("Editar");
        jMenuItemModificarRegistroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarRegistroUsuariosActionPerformed(evt);
            }
        });
        jPopupMenuRegistroUsuarios.add(jMenuItemModificarRegistroUsuarios);

        jMenuItemEliminarRegistroUsuarios.setText("Eliminar");
        jMenuItemEliminarRegistroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarRegistroUsuariosActionPerformed(evt);
            }
        });
        jPopupMenuRegistroUsuarios.add(jMenuItemEliminarRegistroUsuarios);

        jMenuItemVerRecibo.setText("Ver recibo");
        jMenuItemVerRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerReciboActionPerformed(evt);
            }
        });
        jPopupMenuHistorialRecibos.add(jMenuItemVerRecibo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelUsuarios.setBackground(new java.awt.Color(102, 102, 255));
        jPanelUsuarios.setName(""); // NOI18N
        jPanelUsuarios.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelUsuariosComponentShown(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Campos usuario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        jtextFieldUserNombre.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setText("Numero de cliente");

        jLabel4.setText("Numero de contrato");

        jLabel5.setText("Nombre");

        jLabel6.setText("Apellido paterno");

        jtextFieldUserApaterno.setBackground(new java.awt.Color(255, 204, 204));

        jLabel7.setText("Apellido materno");

        jtextFieldUserAmaterno.setBackground(new java.awt.Color(255, 204, 204));

        jtextFieldUserBarrio.setBackground(new java.awt.Color(255, 204, 204));

        jLabel8.setText("Telefono");

        jLabel10.setText("Barrio");

        jLabel11.setText("Domicilio");

        jtextFieldUserDomicilio.setBackground(new java.awt.Color(255, 204, 204));

        botonRegistrarUsuario.setText("Registrar");
        botonRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarUsuarioActionPerformed(evt);
            }
        });

        botonModificarUsuario.setText("Modificar");
        botonModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarUsuarioActionPerformed(evt);
            }
        });

        jLabel12.setText("Tipo descuento");

        jLabel13.setText("Tarifa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtextFieldUserAmaterno)
                                    .addComponent(jtextFieldUserNoCliente)
                                    .addComponent(jComboBoxDescuentos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxTarifas, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtextFieldUserTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtextFieldUserNoContrato)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtextFieldUserBarrio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtextFieldUserNombre)
                            .addComponent(botonRegistrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtextFieldUserDomicilio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtextFieldUserApaterno, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtextFieldUserNoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextFieldUserNoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextFieldUserNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextFieldUserApaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtextFieldUserAmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextFieldUserTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextFieldUserBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextFieldUserDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTarifas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrarUsuario)
                    .addComponent(botonModificarUsuario))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tablaRegistroUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaRegistroUsuarios.setComponentPopupMenu(jPopupMenuRegistroUsuarios);
        jScrollPaneRegistroUsuarios.setViewportView(tablaRegistroUsuarios);

        botonFiltrarUsuarios.setText("Filtrar");
        botonFiltrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFiltrarUsuariosActionPerformed(evt);
            }
        });

        jButtonUsuariosEliminados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userEliminado.png"))); // NOI18N
        jButtonUsuariosEliminados.setText("Usuarios eliminados");
        jButtonUsuariosEliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuariosEliminadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUsuariosLayout = new javax.swing.GroupLayout(jPanelUsuarios);
        jPanelUsuarios.setLayout(jPanelUsuariosLayout);
        jPanelUsuariosLayout.setHorizontalGroup(
            jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneRegistroUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUsuariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonFiltrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUsuariosLayout.createSequentialGroup()
                        .addComponent(jButtonUsuariosEliminados)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelUsuariosLayout.setVerticalGroup(
            jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUsuariosLayout.createSequentialGroup()
                .addComponent(jButtonUsuariosEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(botonFiltrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneRegistroUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuarios", jPanelUsuarios);

        jScrollPaneUsuarios.setAutoscrolls(true);
        jScrollPaneUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Numero del cliente", "Numero de contrato", "Nombre", "Apellido paterno", "Apellido Materno", "Domicilio", "Telefono", "Barrio", "Tipo de descuento", "Tipo de tarifa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaUsuarios.setAutoscrolls(false);
        jScrollPaneUsuarios.setViewportView(tablaUsuarios);

        botonFactura.setText("Generar nueva factura a usuario seleccionado");
        botonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacturaActionPerformed(evt);
            }
        });

        botonM.setText("Mostrar");
        botonM.setToolTipText("");
        botonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255)), "Campos para busqueda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabel9.setText("Nombre");

        jLabel16.setText("Apellido paterno");

        jLabel17.setText("Apellido Materno");

        jLabel18.setText("Domicilio");

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        jLabel19.setText("Barrio");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscadorDomicilio)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(buscadorNombre, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscadorApaterno)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscadorBarrio)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscadorAmaterno)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorApaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorAmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel20.setText("al");

        jLabel21.setText("Ver pagos del:");

        jScrollPane1.setComponentPopupMenu(jPopupMenuUsuarios);

        tablaDetallePagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Forma de pago", "Perido", "estado"
            }
        ));
        tablaDetallePagos.setComponentPopupMenu(jPopupMenuUsuarios);
        jScrollPane1.setViewportView(tablaDetallePagos);

        botonGestionDescuentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cupon.png"))); // NOI18N
        botonGestionDescuentos.setText("Gestionar descuentos");
        botonGestionDescuentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionDescuentosActionPerformed(evt);
            }
        });

        botonGestionTarifas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tarifas-v.png"))); // NOI18N
        botonGestionTarifas.setText("Gestionar tarifas");
        botonGestionTarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionTarifasActionPerformed(evt);
            }
        });

        botonPagoMinimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pago-minimo.png"))); // NOI18N
        botonPagoMinimo.setText("Pago Minimo");
        botonPagoMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagoMinimoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Deuda total:");

        jLabelValueDeudaTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelValueDeudaTotal.setText("0");

        botonRespaldoDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/establecer-backup.png"))); // NOI18N
        botonRespaldoDatos.setText("Respaldar datos");
        botonRespaldoDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRespaldoDatosActionPerformed(evt);
            }
        });

        botonReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        botonReportes.setText("Reportes");
        botonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCobrosLayout = new javax.swing.GroupLayout(jPanelCobros);
        jPanelCobros.setLayout(jPanelCobrosLayout);
        jPanelCobrosLayout.setHorizontalGroup(
            jPanelCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCobrosLayout.createSequentialGroup()
                .addGroup(jPanelCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCobrosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jyearPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jyearPeriodo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonM, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCobrosLayout.createSequentialGroup()
                        .addComponent(botonFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelValueDeudaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanelCobrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonGestionDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGestionTarifas, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonPagoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRespaldoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCobrosLayout.setVerticalGroup(
            jPanelCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCobrosLayout.createSequentialGroup()
                .addGroup(jPanelCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonGestionDescuentos, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(botonGestionTarifas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonPagoMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRespaldoDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jyearPeriodo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jyearPeriodo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonFactura)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelValueDeudaTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("cobros", jPanelCobros);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(51, 204, 255)), "Campos para filtrado de historial de recibos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        botonFiltrarPagos.setText("Filtrar pagos por fecha");
        botonFiltrarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFiltrarPagosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonFiltrarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(528, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonFiltrarPagos)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        tablaHistorialRecibos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaHistorialRecibos.setComponentPopupMenu(jPopupMenuHistorialRecibos);
        jScrollPanePagos.setViewportView(tablaHistorialRecibos);

        botonConsultarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultarPago.png"))); // NOI18N
        botonConsultarPago.setText("Consultar pago");
        botonConsultarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPagosLayout = new javax.swing.GroupLayout(jPanelPagos);
        jPanelPagos.setLayout(jPanelPagosLayout);
        jPanelPagosLayout.setHorizontalGroup(
            jPanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPanePagos, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
            .addGroup(jPanelPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonConsultarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPagosLayout.setVerticalGroup(
            jPanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonConsultarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPanePagos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Recibos de pago", jPanelPagos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMActionPerformed
        // TODO add your handling code here:
        MostrarPagos instancia=new MostrarPagos();
        int fila=tablaUsuarios.getSelectedRow();
        if(fila>=0){
            String idCliente=tablaUsuarios.getValueAt(fila,0).toString();
            instancia.mostrarDetallePagos(idCliente,jyearPeriodo1.getYear(),jyearPeriodo2.getYear(), 
                tablaDetallePagos);
            
            SqlUsuarios instanciaSqlUsuario=new SqlUsuarios();
            float deudaTotal=instanciaSqlUsuario.obtenerDeudaTotalCliente(idCliente,jyearPeriodo1.getYear(),jyearPeriodo2.getYear());
            jLabelValueDeudaTotal.setText(""+deudaTotal);
        }else{
            JOptionPane.showMessageDialog(null,"selecciona un cliente","!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonMActionPerformed

    private void botonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacturaActionPerformed
        // TODO add your handling code here:
        int fila = tablaUsuarios.getSelectedRow();

        if(fila>=0){
            SqlUsuarios usuario = new SqlUsuarios();

            FacturaNueva instancia = new FacturaNueva(this, rootPaneCheckingEnabled);
            String idCliente=tablaUsuarios.getValueAt(fila,0).toString();
            String nombre=tablaUsuarios.getValueAt(fila,3).toString();
            String tipoDescuento=tablaUsuarios.getValueAt(fila,9).toString();
            String tipoTarifa=tablaUsuarios.getValueAt(fila,10).toString();

            float precioTarifa=usuario.obtenerPrecioTarifaDeUsuario(idCliente);
            float cantidadDescuento=usuario.obtenerDescuentoDeUsuario(idCliente);
            FacturaNueva.campoIdCliente.setText(idCliente);
            FacturaNueva.campoNombreCliente.setText(nombre);
            FacturaNueva.campoTipoDescuento.setText(tipoDescuento);
            FacturaNueva.campoTipoTarifa.setText(tipoTarifa);
            FacturaNueva.campoPrecioTarifa.setText(String.valueOf(precioTarifa));
            FacturaNueva.campoDescuento.setText(String.valueOf(cantidadDescuento));
            FacturaNueva.periodo1=jyearPeriodo1.getYear();
            FacturaNueva.periodo2=jyearPeriodo2.getYear();
            instancia.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"no selecciono un registro","Atencion",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonFacturaActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        MostrarUsuarios instanciaMostrarUsuarios = new MostrarUsuarios();
        
        instanciaMostrarUsuarios.mostrarUsuariosCobros(buscadorNombre.getText(),buscadorApaterno.getText(),
            buscadorAmaterno.getText(),buscadorDomicilio.getText(),buscadorBarrio.getText(),tablaUsuarios);
                
        /*inicializamos las Variables staticas para actualizar la tablaPagos en la pestania cobros al actulizar usuarios en la pestania usuarios*/
        nombreStatic=buscadorNombre.getText();apellidoPaternoStatic=buscadorApaterno.getText();
        apellidoMaternoStatic=buscadorAmaterno.getText();domicilioStatic=buscadorDomicilio.getText();
        barrioStatic=buscadorBarrio.getText();
        /*fin de inicalizacion de variables staticas */
  
        buscadorNombre.setText("");buscadorApaterno.setText("");buscadorAmaterno.setText("");
        buscadorDomicilio.setText(""); buscadorBarrio.setText("");
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void jMenuItemCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCobrarActionPerformed
        // TODO add your handling code here:
        
        int filaTablaDetallePagos=tablaDetallePagos.getSelectedRow();
        if(filaTablaDetallePagos>=0){
            SqlUsuarios instanciaUsuarios=new SqlUsuarios();
            HashMap<String, String> datosUsuario;
            String periodo=tablaDetallePagos.getValueAt(filaTablaDetallePagos,3).toString();
            String idCliente=tablaDetallePagos.getValueAt(filaTablaDetallePagos,0).toString();
            VentanaPagos.periodo=periodo;
            VentanaPagos.idCliente=idCliente;
            System.out.println("id cliente-----"+idCliente);
            VentanaPagos instanciaPagos = new VentanaPagos(this, rootPaneCheckingEnabled);
            
            datosUsuario=instanciaUsuarios.obtenerDatosClientes(idCliente);
            
            instanciaPagos.jlabelValueIdCliente.setText(idCliente);
            instanciaPagos.jLabelvalueCliente.setText(datosUsuario.get("nombre")+" "+datosUsuario.get("apellido_paterno")
            +" "+datosUsuario.get("apellido_materno"));
            instanciaPagos.jlabelValueDomicilio.setText(datosUsuario.get("domicilio"));
            instanciaPagos.jlabelValueBarrio.setText(datosUsuario.get("barrio"));
            VentanaPagos.periodo1=jyearPeriodo1.getYear();
            VentanaPagos.periodo2=jyearPeriodo2.getYear();
            
            instanciaPagos.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"seleccione el registro faltante","Atencion",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemCobrarActionPerformed

    private void botonGestionDescuentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionDescuentosActionPerformed
        // TODO add your handling code here:
        VentanaDescuentos instanciaDescuentos=new VentanaDescuentos();
        instanciaDescuentos.setVisible(true);
    }//GEN-LAST:event_botonGestionDescuentosActionPerformed

    private void botonGestionTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionTarifasActionPerformed
        // TODO add your handling code here:
        VentanaTarifas instanciaTarifas = new VentanaTarifas();
        instanciaTarifas.setVisible(true);
    }//GEN-LAST:event_botonGestionTarifasActionPerformed

    private void botonPagoMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagoMinimoActionPerformed
        // TODO add your handling code here:
        VentanaDePagoMinimo instancia=new VentanaDePagoMinimo();
        instancia.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_botonPagoMinimoActionPerformed

    private void botonFiltrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFiltrarUsuariosActionPerformed
        // TODO add your handling code here:
        FiltradoUsuarios instanciaFiltradoUsuarios= new FiltradoUsuarios();
        if(modificando.equals("no")){
            instanciaFiltradoUsuarios.mostrarUsuarios(jtextFieldUserNombre.getText(), jtextFieldUserApaterno.getText(), 
                jtextFieldUserAmaterno.getText(), jtextFieldUserDomicilio.getText(), 
                jtextFieldUserBarrio.getText(), tablaRegistroUsuarios); 
        }else{
            JOptionPane.showMessageDialog(rootPane, "primero termina de modificar el usuario. Si no se desea "
                    + "realizar cambios deje los campos como estan y presione el boton 'modificar'");
        }
 
    }//GEN-LAST:event_botonFiltrarUsuariosActionPerformed

    private void jPanelUsuariosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelUsuariosComponentShown
        // TODO add your handling code here:
        
        jComboBoxDescuentos.removeAllItems();
        instanciaComboBoxUsuarios.mostrarDescuentos(jComboBoxDescuentos);
        jComboBoxTarifas.removeAllItems();
        instanciaComboBoxUsuarios.mostrarTarifas(jComboBoxTarifas);
    }//GEN-LAST:event_jPanelUsuariosComponentShown

    private void botonRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
        SqlUsuarios instanciaUsuarios=new SqlUsuarios();
        FiltradoUsuarios instanciaFiltrado=new FiltradoUsuarios();
        int idUsuario=instanciaUsuarios.registrarUsuario(jtextFieldUserNoCliente.getText(),jtextFieldUserNoContrato.getText(), 
                        jtextFieldUserNombre.getText(),jtextFieldUserApaterno.getText(),jtextFieldUserAmaterno.getText(), 
                        jtextFieldUserDomicilio.getText(),jtextFieldUserTelefono.getText(),jtextFieldUserBarrio.getText(), 
                        jComboBoxDescuentos.getSelectedItem().toString(),jComboBoxTarifas.getSelectedItem().toString());
        instanciaFiltrado.mostrarUsuario_al_Registrar(idUsuario, tablaRegistroUsuarios);
        
        jtextFieldUserNoCliente.setText(""); jtextFieldUserNoContrato.setText("");
        jtextFieldUserNombre.setText(""); jtextFieldUserApaterno.setText("");
        jtextFieldUserAmaterno.setText(""); jtextFieldUserDomicilio.setText("");
        jtextFieldUserTelefono.setText(""); jtextFieldUserBarrio.setText("");
        instanciaComboBoxUsuarios.mostrarDescuentos(jComboBoxDescuentos);
        instanciaComboBoxUsuarios.mostrarTarifas(jComboBoxTarifas);
    }//GEN-LAST:event_botonRegistrarUsuarioActionPerformed

    private void jMenuItemModificarRegistroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarRegistroUsuariosActionPerformed
        // TODO add your handling code here:
        int fila=tablaRegistroUsuarios.getSelectedRow();
        FiltradoUsuarios instanciaFiltrado=new FiltradoUsuarios();
        if(fila>=0){
            modificando="si";
            jMenuItemEliminarRegistroUsuarios.setEnabled(false);
            botonModificarUsuario.setEnabled(true);
            int idUsuario=Integer.parseInt(tablaRegistroUsuarios.getValueAt(fila,0).toString());
            String numeroCliente=tablaRegistroUsuarios.getValueAt(fila,1).toString();
            String numeroContrato=tablaRegistroUsuarios.getValueAt(fila,2).toString();
            String nombre=tablaRegistroUsuarios.getValueAt(fila,3).toString();
            String apellidoPaterno=tablaRegistroUsuarios.getValueAt(fila,4).toString();
            String apellidoMaterno=tablaRegistroUsuarios.getValueAt(fila,5).toString();
            String domicilio=tablaRegistroUsuarios.getValueAt(fila,6).toString();
            String telefono=tablaRegistroUsuarios.getValueAt(fila,7).toString();
            String barrio=tablaRegistroUsuarios.getValueAt(fila,8).toString();
            String descuento=tablaRegistroUsuarios.getValueAt(fila,9).toString();
            String tarifa=tablaRegistroUsuarios.getValueAt(fila,10).toString();
            jtextFieldUserNoCliente.setText(numeroCliente); jtextFieldUserNoContrato.setText(numeroContrato);
            jtextFieldUserNombre.setText(nombre); jtextFieldUserApaterno.setText(apellidoPaterno);
            jtextFieldUserAmaterno.setText(apellidoMaterno); jtextFieldUserDomicilio.setText(domicilio);
            jtextFieldUserTelefono.setText(telefono); jtextFieldUserBarrio.setText(barrio);
            jComboBoxDescuentos.setSelectedItem(descuento);
            jComboBoxTarifas.setSelectedItem(tarifa);
            //mostramos y especificamos unicamente al usuario que sera modificado para eso utilizamos el metodo 'mostrarUsuario_al_registrar'
            instanciaFiltrado.mostrarUsuario_al_Registrar(idUsuario, tablaRegistroUsuarios);
        }else{
            JOptionPane.showMessageDialog(rootPane,"No selecciono un registro","Atencion",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemModificarRegistroUsuariosActionPerformed

    private void botonModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarUsuarioActionPerformed
        // TODO add your handling code here:
        SqlUsuarios instanciaSqlUsuarios=new SqlUsuarios();
        FiltradoUsuarios instanciaFiltradousuarios=new FiltradoUsuarios();
        modificando="no";//varible definida al inicio de la clase
        jMenuItemEliminarRegistroUsuarios.setEnabled(true);
        int fila=0;//la fila es cero ya que unicamente se mostrara el registro a modificar, gracias al evento editar del
        //JpopupMenu en el evento editar de la tablaRegistroUsuarios
        String idCliente=tablaRegistroUsuarios.getValueAt(fila,0).toString();
        String numeroCliente=jtextFieldUserNoCliente.getText();
        String numeroContrato=jtextFieldUserNoContrato.getText();
        String nombre=jtextFieldUserNombre.getText();
        String apellidoPaterno=jtextFieldUserApaterno.getText();
        String apellidoMaterno=jtextFieldUserAmaterno.getText();
        String domicilio=jtextFieldUserDomicilio.getText();
        String telefono=jtextFieldUserTelefono.getText();
        String barrio=jtextFieldUserBarrio.getText();
        String descuento=jComboBoxDescuentos.getSelectedItem().toString();
        String tarifa=jComboBoxTarifas.getSelectedItem().toString();
        
        instanciaSqlUsuarios.modificarUsuario(idCliente, numeroCliente, numeroContrato, nombre, 
            apellidoPaterno,apellidoMaterno, domicilio, telefono, barrio, descuento, tarifa);
        
        instanciaFiltradousuarios.mostrarUsuario_al_Registrar(Integer.parseInt(idCliente),tablaRegistroUsuarios);
        
        jtextFieldUserNoCliente.setText(""); jtextFieldUserNoContrato.setText("");
        jtextFieldUserNombre.setText(""); jtextFieldUserApaterno.setText("");
        jtextFieldUserAmaterno.setText(""); jtextFieldUserDomicilio.setText("");
        jtextFieldUserTelefono.setText(""); jtextFieldUserBarrio.setText("");
        instanciaComboBoxUsuarios.mostrarDescuentos(jComboBoxDescuentos);
        instanciaComboBoxUsuarios.mostrarTarifas(jComboBoxTarifas);
        
        botonModificarUsuario.setEnabled(false);
        
        int filasTablaUsuarios=MainJFrame.tablaUsuarios.getRowCount();
        if(filasTablaUsuarios>0){//tabla usuarios en pestania cobros
            MostrarUsuarios instanciaMostrarUsuarios=new MostrarUsuarios();
            instanciaMostrarUsuarios.mostrarUsuariosCobros(MainJFrame.nombreStatic, 
                MainJFrame.apellidoPaternoStatic,MainJFrame.apellidoMaternoStatic,
                MainJFrame.domicilioStatic,MainJFrame.barrioStatic, MainJFrame.tablaUsuarios);
        }
        
        
        
    }//GEN-LAST:event_botonModificarUsuarioActionPerformed

    private void jMenuItemEliminarRegistroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarRegistroUsuariosActionPerformed
        // TODO add your handling code here:
        SqlUsuarios instanciaSqlUsuarios = new SqlUsuarios();
        FiltradoUsuarios instanciaFiltradousuarios=new FiltradoUsuarios();
        int fila=tablaRegistroUsuarios.getSelectedRow();
        if(fila>=0){
            
            String idUsuario=tablaRegistroUsuarios.getValueAt(fila,0).toString();
            instanciaSqlUsuarios.actualizarEstadoRegistroUsuario(idUsuario,2);
            instanciaFiltradousuarios.mostrarUsuarios(jtextFieldUserNombre.getText(),jtextFieldUserApaterno.getText(), 
                jtextFieldUserAmaterno.getText(),jtextFieldUserDomicilio.getText(),jtextFieldUserBarrio.getText(), tablaRegistroUsuarios);
            
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un usuario a elimianar");
        }
    }//GEN-LAST:event_jMenuItemEliminarRegistroUsuariosActionPerformed

    private void jButtonUsuariosEliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosEliminadosActionPerformed
        // TODO add your handling code here:
        VentanaUsuariosEliminados instancia= new VentanaUsuariosEliminados();
        instancia.setVisible(true);
    }//GEN-LAST:event_jButtonUsuariosEliminadosActionPerformed

    private void botonFiltrarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFiltrarPagosActionPerformed
        // TODO add your handling code here:
        String fecha;
        HistorialPagos historialPago = new HistorialPagos();
        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            fecha = formatoFecha.format(jDateChooser1.getDate());
            historialPago.mostrarHistorialPagos(fecha, tablaHistorialRecibos);
        } catch (NullPointerException vacio) {
            JOptionPane.showMessageDialog(rootPane,"La fecha es invalida o el campo esta vacio","Fecha ivalida",JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonFiltrarPagosActionPerformed

    private void jMenuItemVerReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerReciboActionPerformed
        // TODO add your handling code here:
        HashMap<String,String> recibo;
        InfoRecibo instanciaInfoRecibo=new InfoRecibo();      
        int fila=tablaHistorialRecibos.getSelectedRow();
  
        if(fila>=0){
            
            String idRegistroPago=tablaHistorialRecibos.getValueAt(fila,0).toString();
            
            recibo=instanciaInfoRecibo.datosRecibo(idRegistroPago);
            VentanaRecibo.idPago=recibo.get("idPago");
            VentanaRecibo.idDetallePago=recibo.get("idDetallePago");
            VentanaRecibo.nombreCompleto=recibo.get("nombreCompleto");
            VentanaRecibo.domicilio=recibo.get("domicilio");
            VentanaRecibo.barrio=recibo.get("barrio");
            VentanaRecibo.tipoPago=recibo.get("tipoPago");
            VentanaRecibo.periodo=recibo.get("periodo");
            VentanaRecibo.tipoTarifa=recibo.get("tipoTarifa");
            VentanaRecibo.precioTarifaAnual=Float.parseFloat(recibo.get("precioTarifa"));
            VentanaRecibo.tipoDescuento=recibo.get("tipoDescuento");
            VentanaRecibo.precioTipoDescuentoMensual=Float.parseFloat(recibo.get("precioDescuento"));
            VentanaRecibo.descuentoAnual=recibo.get("descuentoAnual");
            VentanaRecibo.mesDePago= recibo.get("mesDePago");
            VentanaRecibo.fechaPago= recibo.get("fechaPago");
            VentanaRecibo.importe=recibo.get("importe");
            
            VentanaRecibo ventanaRecibo=new VentanaRecibo();
            ventanaRecibo.setVisible(true);
            //if(recibo.get("error").equals("si")) ventanaRecibo.dispose();
             
        }else{
            JOptionPane.showMessageDialog(null,"selecciona un registro","!!",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jMenuItemVerReciboActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        SqlRespaldo instanciaRespaldo=new SqlRespaldo();
        if(instanciaRespaldo.registro_ruta_respaldo()!=true) {
            JOptionPane.showMessageDialog(null,"No hay ninguna ruta registrada para el respaldo automatico","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void botonRespaldoDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRespaldoDatosActionPerformed
        // TODO add your handling code here:
        VentanaRespaldo instancia=new VentanaRespaldo();
        instancia.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_botonRespaldoDatosActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        SqlRespaldo instanciaRespaldo=new SqlRespaldo();
        if(instanciaRespaldo.registro_ruta_respaldo()) {
            RespaldoAutomatico instancia=new RespaldoAutomatico(this, rootPaneCheckingEnabled);
            instancia.setVisible(true);
            System.out.println("sistemacheranaguapotable.MainJFrame.formWindowClosed()");
        }
       
    }//GEN-LAST:event_formWindowClosed

    private void botonConsultarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarPagoActionPerformed
        // TODO add your handling code here:
        ConsultaPago instancia= new ConsultaPago();
        instancia.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_botonConsultarPagoActionPerformed

    private void botonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportesActionPerformed
        // TODO add your handling code here:
        VerReportes verReportes=new VerReportes();
        verReportes.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_botonReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonConsultarPago;
    private javax.swing.JButton botonFactura;
    private javax.swing.JButton botonFiltrarPagos;
    private javax.swing.JButton botonFiltrarUsuarios;
    private javax.swing.JButton botonGestionDescuentos;
    private javax.swing.JButton botonGestionTarifas;
    private javax.swing.JButton botonM;
    private javax.swing.JButton botonModificarUsuario;
    private javax.swing.JButton botonPagoMinimo;
    private javax.swing.JButton botonRegistrarUsuario;
    private javax.swing.JButton botonReportes;
    private javax.swing.JButton botonRespaldoDatos;
    private javax.swing.JTextField buscadorAmaterno;
    private javax.swing.JTextField buscadorApaterno;
    private javax.swing.JTextField buscadorBarrio;
    private javax.swing.JTextField buscadorDomicilio;
    private javax.swing.JTextField buscadorNombre;
    private javax.swing.JButton jButtonUsuariosEliminados;
    private javax.swing.JComboBox<String> jComboBoxDescuentos;
    private javax.swing.JComboBox<String> jComboBoxTarifas;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabelValueDeudaTotal;
    private javax.swing.JMenuItem jMenuItemCobrar;
    private javax.swing.JMenuItem jMenuItemEliminarRegistroUsuarios;
    private javax.swing.JMenuItem jMenuItemModificarRegistroUsuarios;
    private javax.swing.JMenuItem jMenuItemVerRecibo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelCobros;
    private javax.swing.JPanel jPanelPagos;
    private javax.swing.JPanel jPanelUsuarios;
    private javax.swing.JPopupMenu jPopupMenuHistorialRecibos;
    private javax.swing.JPopupMenu jPopupMenuRegistroUsuarios;
    private javax.swing.JPopupMenu jPopupMenuUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPanePagos;
    private javax.swing.JScrollPane jScrollPaneRegistroUsuarios;
    private javax.swing.JScrollPane jScrollPaneUsuarios;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jtextFieldUserAmaterno;
    private javax.swing.JTextField jtextFieldUserApaterno;
    private javax.swing.JTextField jtextFieldUserBarrio;
    private javax.swing.JTextField jtextFieldUserDomicilio;
    private javax.swing.JTextField jtextFieldUserNoCliente;
    private javax.swing.JTextField jtextFieldUserNoContrato;
    private javax.swing.JTextField jtextFieldUserNombre;
    private javax.swing.JTextField jtextFieldUserTelefono;
    private com.toedter.calendar.JYearChooser jyearPeriodo1;
    private com.toedter.calendar.JYearChooser jyearPeriodo2;
    public static javax.swing.JTable tablaDetallePagos;
    private javax.swing.JTable tablaHistorialRecibos;
    private javax.swing.JTable tablaRegistroUsuarios;
    public static javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
