/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacheranaguapotable;


import impresiones.Imprimir;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jafeth888
 */
public class VentanaRecibo extends javax.swing.JFrame {
    public static String idPago;
    public static String idDetallePago;
    public static String nombreCompleto;
    public static String domicilio;
    public static String barrio;
    public static String tipoPago;
    public static String periodo;
    public static String tipoTarifa;
    public static float precioTarifaAnual;//necesario tipo de dato float
    public static String tipoDescuento;
    public static float precioTipoDescuentoMensual;//necesario tipon de dato float
    public static String descuentoAnual;
    public static String mesDePago;
    public static String fechaPago;
    public static String importe;
    
    /**
     * Creates new form InfoRecibo
     */
    public VentanaRecibo() {
        initComponents();
        inicializarValores();
    }
    
    public void inicializarValores(){
        jLabel_idPago.setText(idPago);jLabel_idDetallePago.setText(idDetallePago);
        jLabelNombreCompleto.setText(nombreCompleto);jLabelDomicilio.setText(domicilio);
        jLabelBarrio.setText(barrio);jLabelTipoPago.setText(tipoPago);jLabelPeriodo.setText(periodo);
        
        jLabelTarifa.setText("Tarifa "+tipoPago);
        /*---------TABLA TARIFA------------------------------------*/
        DefaultTableModel modeloTablaTarifa= new DefaultTableModel();
        modeloTablaTarifa.addColumn("Descripcion");
        modeloTablaTarifa.addColumn("importe");
        String datosTablaTarifa [] = new String [2];
        datosTablaTarifa[0]=tipoTarifa;
        if(tipoPago.equals("Mensual")){
            float tarifaMensual=precioTarifaAnual/12;
            datosTablaTarifa[1]=""+tarifaMensual;
        }else{
           datosTablaTarifa[1]=""+precioTarifaAnual; 
        }
        modeloTablaTarifa.addRow(datosTablaTarifa);
        tablaTarifa.setModel(modeloTablaTarifa);
        /*---------FIN TABLA TARIFA------------------------------------*/
        
        /*----------TABLA DESCUENTOS-----------------------------------*/
        DefaultTableModel modeloTablaDescuentos= new DefaultTableModel();
        modeloTablaDescuentos.addColumn("Descripcion");
        modeloTablaDescuentos.addColumn("Descuento");
        String datosTablaDescuentos [] = new String [2];
        datosTablaDescuentos[0]=tipoDescuento;
        
        if(tipoPago.equals("Mensual")){
            datosTablaDescuentos[1]=""+precioTipoDescuentoMensual;
        }else{
            float descuentoAnualCorrespondiente=precioTipoDescuentoMensual*10;
            datosTablaDescuentos[1]=""+descuentoAnualCorrespondiente;
        }
        modeloTablaDescuentos.addRow(datosTablaDescuentos);
        
        datosTablaDescuentos[0]="Descuento Anual";
        datosTablaDescuentos[1]=descuentoAnual;
        
        modeloTablaDescuentos.addRow(datosTablaDescuentos);
        tablaDescuentos.setModel(modeloTablaDescuentos);
        /*------------FIN TABLA DESCUENTOS------------------------------*/
        jLabelMesDePago.setText(mesDePago);jLabelFechaPago.setText(fechaPago);
        jLabel_importeTotal.setText(importe);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_idPago = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_idDetallePago = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNombreCompleto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelDomicilio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelBarrio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelTipoPago = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelPeriodo = new javax.swing.JLabel();
        jLabelTarifa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTarifa = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDescuentos = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabelMesDePago = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelFechaPago = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel_importeTotal = new javax.swing.JLabel();
        jButtonImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Recibo de pago, codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 22, -1, -1));

        jLabel_idPago.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(jLabel_idPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 22, 78, 17));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Numero de factura:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 51, -1, 22));

        jLabel_idDetallePago.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jLabel_idDetallePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 51, 100, 22));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 79, -1, -1));

        jLabelNombreCompleto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jLabelNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 79, 195, 14));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Domicilio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 79, -1, -1));

        jLabelDomicilio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jLabelDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 79, 298, 14));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Barrio:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 77, -1, -1));

        jLabelBarrio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jLabelBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 77, 78, 14));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Tipo pago:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, -1, -1));

        jLabelTipoPago.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jLabelTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 61, 14));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Periodo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabelPeriodo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelPeriodo.setText("2022");
        getContentPane().add(jLabelPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 60, -1));

        jLabelTarifa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTarifa.setText("Tarifa anual");
        getContentPane().add(jLabelTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 120, -1));

        tablaTarifa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaTarifa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 200, 780, 90));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Tipo descuento");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        tablaDescuentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Descuento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaDescuentos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 780, 110));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Mes que se pago:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabelMesDePago.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelMesDePago.setText("jLabel12");
        getContentPane().add(jLabelMesDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Fecha de pago:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        jLabelFechaPago.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelFechaPago.setText("jLabel13");
        getContentPane().add(jLabelFechaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 100, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Importe total:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        jLabel_importeTotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel_importeTotal.setText("jLabel15");
        getContentPane().add(jLabel_importeTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, -1));

        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:
        Imprimir instanciaImprimir=new Imprimir();
        
        instanciaImprimir.imprimirComprobante(idPago, idDetallePago, nombreCompleto, domicilio, barrio, tipoPago, periodo, tipoTarifa,
            precioTarifaAnual, tipoDescuento, precioTipoDescuentoMensual, descuentoAnual, mesDePago, fechaPago, importe);
        this.dispose();
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRecibo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBarrio;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelFechaPago;
    private javax.swing.JLabel jLabelMesDePago;
    private javax.swing.JLabel jLabelNombreCompleto;
    private javax.swing.JLabel jLabelPeriodo;
    private javax.swing.JLabel jLabelTarifa;
    private javax.swing.JLabel jLabelTipoPago;
    private javax.swing.JLabel jLabel_idDetallePago;
    private javax.swing.JLabel jLabel_idPago;
    private javax.swing.JLabel jLabel_importeTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaDescuentos;
    private javax.swing.JTable tablaTarifa;
    // End of variables declaration//GEN-END:variables
}
