/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacheranaguapotable;

import helpers.sql.SqlDetallePagos;
import helpers.sql.SqlPagos;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemacheranaguapotable.bd.ConexionBd;

/**
 *
 * @author jafeth888
 */
public class VentanaPagos extends javax.swing.JDialog {
    ConexionBd cc= ConexionBd.obtenerInstancia();
    Connection cn= cc.conexion();
    public static String idCliente;// variable estatica para mostrar los pagos en relacion al id 
    /**
     * Creates new form VentanaPagos
     */
    public VentanaPagos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mostrarPagosCliente(idCliente);
        //System.out.print(idCliente);
    }
    
    public void mostrarPagosCliente(String idCliente){
        DefaultTableModel modelo= new DefaultTableModel();
 
        modelo.addColumn("Idpago");
        modelo.addColumn("Tarifa");
        modelo.addColumn("Precio Tarifa");
        modelo.addColumn("Tipo descuento");
        modelo.addColumn("descuento");
        modelo.addColumn("pago");
        modelo.addColumn("descuento anual");
        modelo.addColumn("Total");
        modelo.addColumn("Total Pagado");
        modelo.addColumn("Deuda");
        modelo.addColumn("periodo");
        String sql="";
        //table.setModel(modelo);
        jtablePagos.setModel(modelo);
  
        //SELECT id_pago,tipo_tarifa,precio_tarifa,tipo_descuento,descuento,tipo_pago,descuento_anual,total,total_pagado,deuda,periodo FROM `pagos` WHERE fk_id_cliente = 1 AND estado='en deuda'
        sql="SELECT id_pago,tipo_tarifa,precio_tarifa,tipo_descuento,descuento,tipo_pago,descuento_anual,"
                + "total,total_pagado,deuda,periodo FROM `pagos` WHERE fk_id_cliente ='"+idCliente+"' AND fk_id_estado_pago='2'";
        

        Object []datos = new Object [11];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getInt(11);
                modelo.addRow(datos);
            }
            
        } catch (SQLException ex) {
            ex.printStackTrace();
            System.out.println(ex.getMessage());
        }
       
    }
    
    public void mostrarDetallePagos(String idPago){
        DefaultTableModel modelo= new DefaultTableModel();
 
        modelo.addColumn("Id Registro");
        modelo.addColumn("Id Pago");
        modelo.addColumn("Periodo");
        modelo.addColumn("Mes");
        modelo.addColumn("Importe");
        
        String sql="";
        //table.setModel(modelo);
        jtableDetallePagos.setModel(modelo);
  
        //SELECT id_pago,tipo_tarifa,precio_tarifa,tipo_descuento,descuento,tipo_pago,descuento_anual,total,total_pagado,deuda,periodo FROM `pagos` WHERE fk_id_cliente = 1 AND estado='en deuda'
        sql="SELECT id_registro,fk_id_pago,periodo,mes,importe"
                + " FROM detalle_pagos join pagos on pagos.id_pago=detalle_pagos.fk_id_pago "
                + " WHERE fk_id_pago ='"+idPago+"' AND detalle_pagos.fk_id_estado_pago='2'";
        

        Object []datos = new Object [5];
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getInt(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    modelo.addRow(datos);
                }
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                System.out.println(ex.getMessage());
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_idCliente = new javax.swing.JLabel();
        jlabelValueIdCliente = new javax.swing.JLabel();
        jlabelCliente = new javax.swing.JLabel();
        jlabelValueNombre = new javax.swing.JLabel();
        jlabelValueApellidoPaterno = new javax.swing.JLabel();
        jlabelValueApellidoMaterno = new javax.swing.JLabel();
        jlabelDomicilio = new javax.swing.JLabel();
        jlabelValueDomicilio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlabelValueBarrio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablePagos = new javax.swing.JTable();
        jlabelPagos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableDetallePagos = new javax.swing.JTable();
        botonDetalles = new javax.swing.JButton();
        botonCobrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_idCliente.setText("Codigo cliente:");
        label_idCliente.setToolTipText("");

        jlabelValueIdCliente.setText("codigo cliente");

        jlabelCliente.setText("Cliente:");
        jlabelCliente.setToolTipText("");

        jlabelValueNombre.setText("Guillermo");

        jlabelValueApellidoPaterno.setText("Hernandez");

        jlabelValueApellidoMaterno.setText("Quintanilla");

        jlabelDomicilio.setText("Domicilio:");

        jlabelValueDomicilio.setText("Francisco I madero #584 col. lazaro cardenas");

        jLabel1.setText("Barrio");

        jlabelValueBarrio.setText("1");

        jtablePagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtablePagos);

        jlabelPagos.setText("Pagos");

        jLabel2.setText("Detalle Pagos");

        jtableDetallePagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id registro", "Id pago", "Mes", "importe"
            }
        ));
        jScrollPane2.setViewportView(jtableDetallePagos);

        botonDetalles.setText("Ver detalles");
        botonDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetallesActionPerformed(evt);
            }
        });

        botonCobrar.setText("Cobrar");
        botonCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCobrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_idCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlabelValueIdCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabelCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlabelValueNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlabelValueApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlabelValueApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlabelDomicilio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlabelValueDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlabelValueBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlabelPagos)
                            .addComponent(jLabel2))
                        .addGap(0, 265, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonDetalles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCobrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_idCliente)
                    .addComponent(jlabelValueIdCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelCliente)
                    .addComponent(jlabelValueNombre)
                    .addComponent(jlabelValueApellidoPaterno)
                    .addComponent(jlabelValueApellidoMaterno)
                    .addComponent(jlabelDomicilio)
                    .addComponent(jlabelValueDomicilio)
                    .addComponent(jLabel1)
                    .addComponent(jlabelValueBarrio))
                .addGap(45, 45, 45)
                .addComponent(jlabelPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonDetalles)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCobrar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jlabelValueIdCliente.getAccessibleContext().setAccessibleName("codigoPago");
        jlabelValueIdCliente.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetallesActionPerformed
        // TODO add your handling code here:
        int fila = jtablePagos.getSelectedRow();
        if(fila>=0){
            String idPago=jtablePagos.getValueAt(fila,0).toString();
            //System.out.print(idPago);
            mostrarDetallePagos(idPago);
        }else{
            JOptionPane.showMessageDialog(null,"no selecciono un registro","Atencion",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonDetallesActionPerformed

    private void botonCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCobrarActionPerformed
        // TODO add your handling code here:
        
        int filasDetallePagos=jtableDetallePagos.getRowCount();
        if(filasDetallePagos>0){
           SqlPagos pago = new SqlPagos();
           SqlDetallePagos detallePago=new SqlDetallePagos();
           String idRegistro=jtableDetallePagos.getValueAt(0,0).toString();
           String idPago=jtableDetallePagos.getValueAt(0,1).toString();
           String cadenaImporte=jtableDetallePagos.getValueAt(0,4).toString();
           String cadenaPagoRecibido;
           String fechaPago=LocalDate.now().toString();
           
           float cambio;
           float pagoRecibido;
           float importe;
           
           try{
                cadenaPagoRecibido=JOptionPane.showInputDialog("pago recibido");
                pagoRecibido=Float.parseFloat(cadenaPagoRecibido);
           }catch(Exception e){
               
               //System.out.print(e.getMessage());
               System.err.println("Ventana cerrada!!");
               return;
           }
           
           importe=Float.parseFloat(cadenaImporte);
           
           cambio=pagoRecibido-importe;
           
           /*validacion que el pago se mayor al importe*/
           if(pagoRecibido<importe){
               JOptionPane.showMessageDialog(rootPane,"el pago recibido es menor que el importe",
                    "advertencia",JOptionPane.WARNING_MESSAGE);
               return ;
           }
           
           detallePago.cobrarImporteDetallePagos(idRegistro, cadenaPagoRecibido,String.valueOf(cambio), 
                   fechaPago,1);
           
           float totalTablaPagos;//esta variable representa el total a pagar de una factura, aplicado los descuentos
           float sumatoriaImportesPagadosTablaDetallePagos;
           float deuda;
           
           totalTablaPagos=pago.obtenerTotalPago(idPago);
           sumatoriaImportesPagadosTablaDetallePagos=detallePago.obtenerSumatoriaImportesPagadosTablaDetallePagos(idPago);
           deuda=totalTablaPagos-sumatoriaImportesPagadosTablaDetallePagos;
           pago.actualizarDeudaRegistroPago(idPago,sumatoriaImportesPagadosTablaDetallePagos, deuda);
           
           if(deuda==0){
             pago.actualizarEstadoRegistroPago(idPago,1);
           }
           
           mostrarPagosCliente(idCliente);
           mostrarDetallePagos(idPago);
           
           System.out.println("id pago-- "+idPago);
           System.out.println(sumatoriaImportesPagadosTablaDetallePagos);
           System.out.println(deuda);
           
        }
    }//GEN-LAST:event_botonCobrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaPagos dialog = new VentanaPagos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCobrar;
    private javax.swing.JButton botonDetalles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabelCliente;
    private javax.swing.JLabel jlabelDomicilio;
    private javax.swing.JLabel jlabelPagos;
    public static javax.swing.JLabel jlabelValueApellidoMaterno;
    public static javax.swing.JLabel jlabelValueApellidoPaterno;
    public static javax.swing.JLabel jlabelValueBarrio;
    public static javax.swing.JLabel jlabelValueDomicilio;
    public static javax.swing.JLabel jlabelValueIdCliente;
    public static javax.swing.JLabel jlabelValueNombre;
    private javax.swing.JTable jtableDetallePagos;
    private javax.swing.JTable jtablePagos;
    private javax.swing.JLabel label_idCliente;
    // End of variables declaration//GEN-END:variables
}
